@startuml Objekt model
top to bottom direction
skinparam minClassWidth 125
skinparam nodesep 10
skinparam ranksep 10
skinparam rectangle {
  
  BackgroundColor<<Apache>> LightCoral
  BorderColor<<Apache>> #FF6655
  FontName Courier
  BorderColor black
  BackgroundColor lightGrey
  
}
rectangle Bane{
    map "**Bane1**" as B1{
        Længde => 18
        Brede => 25
    }
}
rectangle Sværhedsgrad {
    map "**Sværhedsgrad1**" as S1{
        Tekst => Begynder
    }
    map "**Sværhedsgrad2**" as S2{
        Tekst => Øvet
    }
    map "**Sværhedsgrad3**" as S3{
        Tekst => Ekspert
    }
    map "**Sværhedsgrad4**" as S4{
        Tekst => Champion
    }
    map "**Sværhedsgrad5**" as S5{
        Tekst => Åben
    }
}

rectangle Øvrige_Elementer{

    map "**Ø_Element1**" as Ø1{
        Type => Spand
    }
    map "**Ø_Element2**" as Ø2{
        Type => kegle
    }
    
}

rectangle Pile{

    map "**Pil1**" as Pil1{
        Retning => Højre mod venstre
        Højreposition => Nej
        Længde => 5m
        Billede =>  Jeps
    }
}

rectangle Skilt{
    map "**Skilt**" as Skilt1{
            Nummer => 3
            Tekst =>højre sving
            Billede =>  Jeps
        }
}
rectangle Dato{
    map "**Dato1**" as Dato1{
            Dato => 20-05-2025
        }
}

rectangle Bane{
    map "**Bane1**" as Bane1{
            Navn => Lenes Bane
            Højde => 18 m
            Bredde => 25 m
        }
}
rectangle Placering{
    map "**Placering1**" as Placering1{
            x => 5
            y => 10
        }
        map "**Placering2**" as Placering2{
            x => 25
            y => 11
        }
}
rectangle Rækkefølge{
    map "**Rækkefølge1**" as Rækkefølge1{
            Nummer => 1
        }
    map "**Rækkefølge2**" as Rækkefølge2{
            Nummer => 2
        }
    map "**Rækkefølge3**" as Rækkefølge3{
            Nummer => 3
        }
}

Rækkefølge1 -- Skilt1
Skilt1 -- Placering1
Skilt1 -- Bane1
Bane1 -- Dato1
Bane1 -- Pil1
Pil1 -- Placering2
Bane1 -- Ø1
S1 -- Bane1
@enduml