@startuml Objekt model
top to bottom direction
skinparam minClassWidth 125
skinparam nodesep 10
skinparam ranksep 10
skinparam rectangle {
  
  BackgroundColor<<Apache>> LightCoral
  BorderColor<<Apache>> #FF6655
  FontName Courier
  BorderColor black
  BackgroundColor lightGrey
  
}
rectangle Baner{
    object Bane1{
        Længde = 18
        Brede = 25
    }
}
rectangle Sværhedsgrad {
    object sværhedsgrad1{
        Åben
    }
}

rectangle BaneElementer{
    object Element1{
        Billede tal = 1
        Rækkefølge tal = 0
        tekst = start 
        Billede
        Placering = Der
        Niveau = Start
    }

    object Element2{
        Billede tal = 301
        Rækkefølge tal = 1
        Text = 90 Venstre sideskift om kegle
        Billede
        Placering = Der
        Niveau = Champion
    }
    object Element3{
        Billede tal = 30
        Rækkefølge tal = 2
        text = 8 tal
        Billede
        Placering = Der
        Niveau = Begynder
    }
    map "**Element4**" as E4 {
        Billede tal => 225
        Rækkefølge tal => 3
        Tekst => Sideskift bagved
        Billede =>
        Placering => Der
        Niveau => Øvet
    }

}

rectangle Pile{

    object Pil1{
        Retning = Højre mod venstre
        Højreposition = Nej
        Længde = 5m
        Placering = Der
        Billede
    }
    object Pil2{
        Retning = Top til bund
        Højreposition = Ja
        Længde = 5m
        Placering = Der
        Billede
    }
    object Pil3{
        Retning = Top til Bund
        Højreposition = Ja
        Længde = 1,5 m
        Placering = Der
        Billede
    }
}
rectangle Øvrige_Elementer{
    object kegle{
        Billede
        Placering
    }
}
Baner -- Pile
Baner -- BaneElementer
Baner -- Øvrige_Elementer
BaneElementer -- Sværhedsgrad
Element1 -- Pil1
Element2 -- Pil1
Element2 -- kegle
Element2 -- Pil2
Element3 -- Pil2 
Element3 -- Pil3
E4 -- Pil3
@enduml