@startuml DCD
rectangle Model_layer {
    rectangle Repositories{  
        note top of GenericRepository : Creating a Generic Repo reduces redundancy
        class "GenericRepository"{
            --Methods--
            + Get(): IReadOnlyList<T>
            + GetById(int id) <T>
            + Create(T entity) : void
            + Update(T entity) : void
            + Delete(T entity) : void
        }
        note top of IGenericRepository : interface is used for loose coupling
        interface "IGenericRepository"{
            --Methods--
            + Get(): IReadOnlyList<T>
            + GetById(int id) <T>
            + Create(T entity) : void
            + Update(T entity) : void
            + Delete(T entity) : void
        }
        note top of RallyRepo : rally, sign and extra repo \n inherits from Generic Repository
        class "RallyRepo"{
        }
        class "SignRepo"{
        }
        class "ExtraRepo"{
        }
        class "ItemListRepo"{
        }
        
        class "DbContext"{
            --Properties--
            + Rally : DbSet<Rally>
            + Sign : DbSet<Sign>
            + Extra : DbSet<Extra>
            --Methods--
            + OnConfiguring(DbContextOptionbuilder optionsBuilder)
            + OnModelCreating(ModelBuilder modelbuilder)
        }
        circle "Model Connection" as ExtraModelConnection{}
        circle "Model Connection" as RallyModelConnection{}
        circle "Model Connection" as SignModelConnection{}
        circle "Model Connection" as ItemListModelConnection{}
 
    }
    rectangle Domain {
        
        circle "Repo Connection" as RallyRepoConnection{}
        class "Rally"{
            --Properties--
            + Id : int
            + Name : string
            + Height : int
            + Width : int
            + ItemList : ItemList
            + Date : date
            + Level : Level
            + Category : string
            --Constructor--
            + Rally()
            + Rally(Name, Height, Width, Level, ItemList, Date)

        }
        
        class "Date"{
            --Properties--
            + Id : int
            + Date : DateTime
        }

        circle "Repo Connection" as ItemListConnection{}
        class "ItemList"{
            --Properties--
            + Id : int
            + Items : IItems
            + Number : int
            + Sign : Sign
            + Extra : Extra
            --Methods--
            + SortingItemList() : List<IItem>
        }

        rectangle items {
            circle "Repo Connection" as ExtraRepoConnection{}
            circle "Repo Connection" as SignRepoConnection{}
            
            class "Sign"{
                --Properties--
                + Id : int
                + Number : int
                + Description : string
                + Image : string
                + Placement : Placement
                + Difficulty : Difficulty
            }   

            class "Difficulty"{
                --Properties--
                + Id : int
                + name : string
            }
            class "Extra"{
                --Properties--
                + Id : int
                + Name : string
                + Description : string
                + Image : string
                + Placement : Placement
            }
            interface IItem{
                --Properties--
                - Id : int
                - Number : int
                - Description : string
                - Image : string
                - Placement : Placement
                
            }
            class "Placement"{
                --Properties--
                + Id : int
                + X_Koordinat
                + Y_Koordinat
            }
        }  
    }
}

rectangle Controller_layer{
    Class RallyController{
        + CreateRally (Name : string, Height : int, Width : int, level : enum, ItemList : itemList, Date : DateTime)
        + ReadRally (Name : string)
        + UpdateRally (Id : int)
        + DeleteRally(Id : int)
        + GetAll(): List<Rally>
    }
}
rectangle View{
    class "Views"{
    }
}

RallyRepo --> GenericRepository
ItemListRepo --> GenericRepository
ExtraRepo --> GenericRepository
SignRepo --> GenericRepository
GenericRepository --> IGenericRepository
IGenericRepository--> DbContext
ExtraRepoConnection .. Extra
ExtraModelConnection . ExtraRepo
SignRepoConnection .. Sign
SignModelConnection . SignRepo
RallyModelConnection . RallyRepo
RallyRepoConnection . Rally
ItemListModelConnection . ItemListRepo
ItemListConnection . ItemList


Rally --|>  Date
Rally --|> ItemList
ItemList --|> IItem
IItem <-- Sign
IItem <-- Extra
Sign  --|> Placement
Difficulty <|-- Sign
Extra  --|> Placement

@enduml