@startuml UseCase Diagram
skinparam actorStyle awesome
left to right direction
actor lene as lene
rectangle use_cases{
    
    usecase "Opret bruger" as UC2
    usecase "Logger ind" as UC3
    usecase "Opretter bane" as UC4  
    usecase "Deler bane" as UC5  
    
}

lene --> UC2
lene --> UC3
lene --> UC4
lene --> UC5

@enduml

