@startuml Opretter Bane
title Opret bane \n SSD 
skinparam style strictuml
actor lene as lene
participant system as sys

lene -> sys : Tilgår system
lene <-- sys : Viser inputside
lene -> sys : Vælger type af bane
lene -> sys : Opretter bane
lene <-- sys : Viser "Opret Bane" inputside
loop until user ends
lene -> sys : Placerer skilte element
sys->sys:Registrer placering
end
lene -> sys : Afslutter opret bane 
lene <-- sys : bekræftelses besked

@enduml