@startuml Dele Bane
title Dele bane\n SSD
skinparam style strictuml
actor Bruger
Bruger -> System: Tilgår System
System --> Bruger: Viser inputside(Bane)
loop indtil bruger afslutter
Bruger ->System: Vælg bane
System->System:Registrer valg
end
System-->Bruger:Liste af valgte baner
loop indtil bruger afslutter 
Bruger -> System: Vælg bruger
System->System:Registrer valg
end
System-->Bruger:Oversigt over valg
Bruger -> System:Del
System --> Bruger: Bekræftelse

@enduml