@startuml Opretter Bane
title Opret bane \n SSD 
skinparam style strictuml
actor Bruger
participant System as sys

Bruger-> sys : Tilgår system
Bruger <-- sys : Viser inputside
Bruger -> sys : Vælger type af bane
Bruger -> sys : Opretter bane
Bruger <-- sys : Viser "Opret Bane" inputside
loop indtil bruger afslutter
Bruger -> sys : Placerer skilte element
sys->sys:Registrer placering
end
Bruger -> sys : Afslutter opret bane 
Bruger <-- sys : bekræftelses besked

@enduml