// <auto-generated />
using DogApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogApp.Modellayer.EntityModels.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description of Sign 1",
                            Image = "hest",
                            ItemCategory = 0,
                            Name = "Sign 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description of Sign 2",
                            Image = "hest",
                            ItemCategory = 0,
                            Name = "Sign 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description of Sign 3",
                            Image = "hest",
                            ItemCategory = 0,
                            Name = "Sign 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description of Sign 4",
                            Image = "hest",
                            ItemCategory = 0,
                            Name = "Sign 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description of Sign 5",
                            Image = "hest",
                            ItemCategory = 0,
                            Name = "Sign 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description of Extra 1",
                            Image = "hest",
                            ItemCategory = 1,
                            Name = "Extra 1"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description of Extra 2",
                            Image = "hest",
                            ItemCategory = 1,
                            Name = "Extra 2"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description of Extra 3",
                            Image = "hest",
                            ItemCategory = 1,
                            Name = "Extra 3"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description of Extra 4",
                            Image = "hest",
                            ItemCategory = 1,
                            Name = "Extra 4"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description of Extra 5",
                            Image = "hest",
                            ItemCategory = 1,
                            Name = "Extra 5"
                        });
                });

            modelBuilder.Entity("DogApp.Modellayer.EntityModels.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Category A",
                            Height = 100,
                            Name = "Rally 1",
                            Width = 200
                        },
                        new
                        {
                            Id = 2,
                            Category = "Category B",
                            Height = 150,
                            Name = "Rally 2",
                            Width = 250
                        },
                        new
                        {
                            Id = 3,
                            Category = "Category C",
                            Height = 120,
                            Name = "Rally 3",
                            Width = 180
                        });
                });

            modelBuilder.Entity("DogApp.Modellayer.EntityModels.TrackItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Itemid")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Trackid")
                        .HasColumnType("int");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Itemid");

                    b.HasIndex("Trackid");

                    b.ToTable("TrackItems");
                });

            modelBuilder.Entity("DogApp.Modellayer.EntityModels.TrackItem", b =>
                {
                    b.HasOne("DogApp.Modellayer.EntityModels.Item", null)
                        .WithMany("TrackItems")
                        .HasForeignKey("Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogApp.Modellayer.EntityModels.Track", null)
                        .WithMany("TrackItems")
                        .HasForeignKey("Trackid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DogApp.Modellayer.EntityModels.Item", b =>
                {
                    b.Navigation("TrackItems");
                });

            modelBuilder.Entity("DogApp.Modellayer.EntityModels.Track", b =>
                {
                    b.Navigation("TrackItems");
                });
#pragma warning restore 612, 618
        }
    }
}
